export const COMPLETE_POKEMON_INFO = "POKEMON/ADD_POKEMON";
export const SET_ALL_POKEMON = "POKEMON/SET_ALL_POKEMON_HEADER_DATA";
export const POKEDEX_SET_PAGE_SIZE = "POKEMON/POKEDEX_SET_PAGE_SIZE";
export const POKEDEX_CHANGE_NEXT_PAGE = "POKEMON/POKEDEX_CHANGE_NEXT_PAGE";
export const POKEDEX_CHANGE_PREV_PAGE = "POKEMON/POKEDEX_CHANGE_PREV_PAGE";
